version: "3.8"
services:
  php:
    build: ./docker/php
    volumes:
      - ./work:/work

  web:
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./work:/work
    working_dir: /work

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - db
    ports:
      - 3001:80

volumes:
  db-store:
